//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/Scripts/Input/GameInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Input/GameInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputActions"",
    ""maps"": [
        {
            ""name"": ""None"",
            ""id"": ""78bffde1-a878-4219-8dee-9fb794d707d1"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""UI_PopupTest"",
            ""id"": ""50e2ee2f-f5aa-4776-b4e3-f3998e679a96"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""8b2b8373-d163-4925-97c9-4204df7146f6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9f8bf28d-3bfd-4489-8130-cc5d51d2594e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI_ItemDetailPopup"",
            ""id"": ""3e0a6d3d-5c38-4831-b226-2282c3dafcd1"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""d14020b9-02d5-456c-b51d-ebb7f4604234"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7da74c52-012e-44f0-8c0e-f1264fb6d3b4"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI_TabGroupPopup"",
            ""id"": ""8acbc424-34ab-41f7-bb47-5fbb17e1c786"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""887eb40b-82a8-4723-9f09-4c4f617a24cf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1357d439-5df5-4c36-ab81-f68392bcaa83"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI_MissionPopup"",
            ""id"": ""e650f4dc-bbce-4571-a8ac-f4bc304b7a08"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""ea6b5e42-3429-4d91-8587-edabc2c29cf0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4306c2c7-ddfc-4d01-b5e9-c0011e6c9bf1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI_NikkeCardSortFilter"",
            ""id"": ""9ae90bf2-4847-44f4-aa15-9a57bae3a6d1"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""134b74cd-2015-4a7d-9c6d-38a911e6c96d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""955fd451-678f-4194-b30a-53b215a8bf91"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI_NikkeDetailPopup"",
            ""id"": ""bc72aa99-a4ca-45a9-ac84-ab0785328e13"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""e86125bb-e215-4b45-98fa-1f6a2b50d7ae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""931fa591-d8f7-483b-a2cb-5aca3b1d30ef"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI_NikkeLevelUpPopup"",
            ""id"": ""553d065e-d2b8-492b-ad43-ff2002d67f78"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""bacef153-610e-412b-a25c-03cad1018719"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d51ec017-95b4-444f-ba1a-5a763a94f373"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // None
        m_None = asset.FindActionMap("None", throwIfNotFound: true);
        // UI_PopupTest
        m_UI_PopupTest = asset.FindActionMap("UI_PopupTest", throwIfNotFound: true);
        m_UI_PopupTest_Close = m_UI_PopupTest.FindAction("Close", throwIfNotFound: true);
        // UI_ItemDetailPopup
        m_UI_ItemDetailPopup = asset.FindActionMap("UI_ItemDetailPopup", throwIfNotFound: true);
        m_UI_ItemDetailPopup_Close = m_UI_ItemDetailPopup.FindAction("Close", throwIfNotFound: true);
        // UI_TabGroupPopup
        m_UI_TabGroupPopup = asset.FindActionMap("UI_TabGroupPopup", throwIfNotFound: true);
        m_UI_TabGroupPopup_Close = m_UI_TabGroupPopup.FindAction("Close", throwIfNotFound: true);
        // UI_MissionPopup
        m_UI_MissionPopup = asset.FindActionMap("UI_MissionPopup", throwIfNotFound: true);
        m_UI_MissionPopup_Close = m_UI_MissionPopup.FindAction("Close", throwIfNotFound: true);
        // UI_NikkeCardSortFilter
        m_UI_NikkeCardSortFilter = asset.FindActionMap("UI_NikkeCardSortFilter", throwIfNotFound: true);
        m_UI_NikkeCardSortFilter_Close = m_UI_NikkeCardSortFilter.FindAction("Close", throwIfNotFound: true);
        // UI_NikkeDetailPopup
        m_UI_NikkeDetailPopup = asset.FindActionMap("UI_NikkeDetailPopup", throwIfNotFound: true);
        m_UI_NikkeDetailPopup_Close = m_UI_NikkeDetailPopup.FindAction("Close", throwIfNotFound: true);
        // UI_NikkeLevelUpPopup
        m_UI_NikkeLevelUpPopup = asset.FindActionMap("UI_NikkeLevelUpPopup", throwIfNotFound: true);
        m_UI_NikkeLevelUpPopup_Close = m_UI_NikkeLevelUpPopup.FindAction("Close", throwIfNotFound: true);
    }

    ~@GameInputActions()
    {
        UnityEngine.Debug.Assert(!m_None.enabled, "This will cause a leak and performance issues, GameInputActions.None.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI_PopupTest.enabled, "This will cause a leak and performance issues, GameInputActions.UI_PopupTest.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI_ItemDetailPopup.enabled, "This will cause a leak and performance issues, GameInputActions.UI_ItemDetailPopup.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI_TabGroupPopup.enabled, "This will cause a leak and performance issues, GameInputActions.UI_TabGroupPopup.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI_MissionPopup.enabled, "This will cause a leak and performance issues, GameInputActions.UI_MissionPopup.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI_NikkeCardSortFilter.enabled, "This will cause a leak and performance issues, GameInputActions.UI_NikkeCardSortFilter.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI_NikkeDetailPopup.enabled, "This will cause a leak and performance issues, GameInputActions.UI_NikkeDetailPopup.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI_NikkeLevelUpPopup.enabled, "This will cause a leak and performance issues, GameInputActions.UI_NikkeLevelUpPopup.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // None
    private readonly InputActionMap m_None;
    private List<INoneActions> m_NoneActionsCallbackInterfaces = new List<INoneActions>();
    /// <summary>
    /// Provides access to input actions defined in input action map "None".
    /// </summary>
    public struct NoneActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public NoneActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_None; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="NoneActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(NoneActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="NoneActions" />
        public void AddCallbacks(INoneActions instance)
        {
            if (instance == null || m_Wrapper.m_NoneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NoneActionsCallbackInterfaces.Add(instance);
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="NoneActions" />
        private void UnregisterCallbacks(INoneActions instance)
        {
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="NoneActions.UnregisterCallbacks(INoneActions)" />.
        /// </summary>
        /// <seealso cref="NoneActions.UnregisterCallbacks(INoneActions)" />
        public void RemoveCallbacks(INoneActions instance)
        {
            if (m_Wrapper.m_NoneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="NoneActions.AddCallbacks(INoneActions)" />
        /// <seealso cref="NoneActions.RemoveCallbacks(INoneActions)" />
        /// <seealso cref="NoneActions.UnregisterCallbacks(INoneActions)" />
        public void SetCallbacks(INoneActions instance)
        {
            foreach (var item in m_Wrapper.m_NoneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NoneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="NoneActions" /> instance referencing this action map.
    /// </summary>
    public NoneActions @None => new NoneActions(this);

    // UI_PopupTest
    private readonly InputActionMap m_UI_PopupTest;
    private List<IUI_PopupTestActions> m_UI_PopupTestActionsCallbackInterfaces = new List<IUI_PopupTestActions>();
    private readonly InputAction m_UI_PopupTest_Close;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI_PopupTest".
    /// </summary>
    public struct UI_PopupTestActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UI_PopupTestActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI_PopupTest/Close".
        /// </summary>
        public InputAction @Close => m_Wrapper.m_UI_PopupTest_Close;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI_PopupTest; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UI_PopupTestActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UI_PopupTestActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UI_PopupTestActions" />
        public void AddCallbacks(IUI_PopupTestActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_PopupTestActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_PopupTestActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UI_PopupTestActions" />
        private void UnregisterCallbacks(IUI_PopupTestActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UI_PopupTestActions.UnregisterCallbacks(IUI_PopupTestActions)" />.
        /// </summary>
        /// <seealso cref="UI_PopupTestActions.UnregisterCallbacks(IUI_PopupTestActions)" />
        public void RemoveCallbacks(IUI_PopupTestActions instance)
        {
            if (m_Wrapper.m_UI_PopupTestActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UI_PopupTestActions.AddCallbacks(IUI_PopupTestActions)" />
        /// <seealso cref="UI_PopupTestActions.RemoveCallbacks(IUI_PopupTestActions)" />
        /// <seealso cref="UI_PopupTestActions.UnregisterCallbacks(IUI_PopupTestActions)" />
        public void SetCallbacks(IUI_PopupTestActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_PopupTestActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_PopupTestActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UI_PopupTestActions" /> instance referencing this action map.
    /// </summary>
    public UI_PopupTestActions @UI_PopupTest => new UI_PopupTestActions(this);

    // UI_ItemDetailPopup
    private readonly InputActionMap m_UI_ItemDetailPopup;
    private List<IUI_ItemDetailPopupActions> m_UI_ItemDetailPopupActionsCallbackInterfaces = new List<IUI_ItemDetailPopupActions>();
    private readonly InputAction m_UI_ItemDetailPopup_Close;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI_ItemDetailPopup".
    /// </summary>
    public struct UI_ItemDetailPopupActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UI_ItemDetailPopupActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI_ItemDetailPopup/Close".
        /// </summary>
        public InputAction @Close => m_Wrapper.m_UI_ItemDetailPopup_Close;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI_ItemDetailPopup; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UI_ItemDetailPopupActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UI_ItemDetailPopupActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UI_ItemDetailPopupActions" />
        public void AddCallbacks(IUI_ItemDetailPopupActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_ItemDetailPopupActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_ItemDetailPopupActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UI_ItemDetailPopupActions" />
        private void UnregisterCallbacks(IUI_ItemDetailPopupActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UI_ItemDetailPopupActions.UnregisterCallbacks(IUI_ItemDetailPopupActions)" />.
        /// </summary>
        /// <seealso cref="UI_ItemDetailPopupActions.UnregisterCallbacks(IUI_ItemDetailPopupActions)" />
        public void RemoveCallbacks(IUI_ItemDetailPopupActions instance)
        {
            if (m_Wrapper.m_UI_ItemDetailPopupActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UI_ItemDetailPopupActions.AddCallbacks(IUI_ItemDetailPopupActions)" />
        /// <seealso cref="UI_ItemDetailPopupActions.RemoveCallbacks(IUI_ItemDetailPopupActions)" />
        /// <seealso cref="UI_ItemDetailPopupActions.UnregisterCallbacks(IUI_ItemDetailPopupActions)" />
        public void SetCallbacks(IUI_ItemDetailPopupActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_ItemDetailPopupActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_ItemDetailPopupActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UI_ItemDetailPopupActions" /> instance referencing this action map.
    /// </summary>
    public UI_ItemDetailPopupActions @UI_ItemDetailPopup => new UI_ItemDetailPopupActions(this);

    // UI_TabGroupPopup
    private readonly InputActionMap m_UI_TabGroupPopup;
    private List<IUI_TabGroupPopupActions> m_UI_TabGroupPopupActionsCallbackInterfaces = new List<IUI_TabGroupPopupActions>();
    private readonly InputAction m_UI_TabGroupPopup_Close;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI_TabGroupPopup".
    /// </summary>
    public struct UI_TabGroupPopupActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UI_TabGroupPopupActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI_TabGroupPopup/Close".
        /// </summary>
        public InputAction @Close => m_Wrapper.m_UI_TabGroupPopup_Close;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI_TabGroupPopup; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UI_TabGroupPopupActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UI_TabGroupPopupActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UI_TabGroupPopupActions" />
        public void AddCallbacks(IUI_TabGroupPopupActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_TabGroupPopupActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_TabGroupPopupActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UI_TabGroupPopupActions" />
        private void UnregisterCallbacks(IUI_TabGroupPopupActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UI_TabGroupPopupActions.UnregisterCallbacks(IUI_TabGroupPopupActions)" />.
        /// </summary>
        /// <seealso cref="UI_TabGroupPopupActions.UnregisterCallbacks(IUI_TabGroupPopupActions)" />
        public void RemoveCallbacks(IUI_TabGroupPopupActions instance)
        {
            if (m_Wrapper.m_UI_TabGroupPopupActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UI_TabGroupPopupActions.AddCallbacks(IUI_TabGroupPopupActions)" />
        /// <seealso cref="UI_TabGroupPopupActions.RemoveCallbacks(IUI_TabGroupPopupActions)" />
        /// <seealso cref="UI_TabGroupPopupActions.UnregisterCallbacks(IUI_TabGroupPopupActions)" />
        public void SetCallbacks(IUI_TabGroupPopupActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_TabGroupPopupActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_TabGroupPopupActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UI_TabGroupPopupActions" /> instance referencing this action map.
    /// </summary>
    public UI_TabGroupPopupActions @UI_TabGroupPopup => new UI_TabGroupPopupActions(this);

    // UI_MissionPopup
    private readonly InputActionMap m_UI_MissionPopup;
    private List<IUI_MissionPopupActions> m_UI_MissionPopupActionsCallbackInterfaces = new List<IUI_MissionPopupActions>();
    private readonly InputAction m_UI_MissionPopup_Close;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI_MissionPopup".
    /// </summary>
    public struct UI_MissionPopupActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UI_MissionPopupActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI_MissionPopup/Close".
        /// </summary>
        public InputAction @Close => m_Wrapper.m_UI_MissionPopup_Close;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI_MissionPopup; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UI_MissionPopupActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UI_MissionPopupActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UI_MissionPopupActions" />
        public void AddCallbacks(IUI_MissionPopupActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_MissionPopupActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_MissionPopupActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UI_MissionPopupActions" />
        private void UnregisterCallbacks(IUI_MissionPopupActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UI_MissionPopupActions.UnregisterCallbacks(IUI_MissionPopupActions)" />.
        /// </summary>
        /// <seealso cref="UI_MissionPopupActions.UnregisterCallbacks(IUI_MissionPopupActions)" />
        public void RemoveCallbacks(IUI_MissionPopupActions instance)
        {
            if (m_Wrapper.m_UI_MissionPopupActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UI_MissionPopupActions.AddCallbacks(IUI_MissionPopupActions)" />
        /// <seealso cref="UI_MissionPopupActions.RemoveCallbacks(IUI_MissionPopupActions)" />
        /// <seealso cref="UI_MissionPopupActions.UnregisterCallbacks(IUI_MissionPopupActions)" />
        public void SetCallbacks(IUI_MissionPopupActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_MissionPopupActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_MissionPopupActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UI_MissionPopupActions" /> instance referencing this action map.
    /// </summary>
    public UI_MissionPopupActions @UI_MissionPopup => new UI_MissionPopupActions(this);

    // UI_NikkeCardSortFilter
    private readonly InputActionMap m_UI_NikkeCardSortFilter;
    private List<IUI_NikkeCardSortFilterActions> m_UI_NikkeCardSortFilterActionsCallbackInterfaces = new List<IUI_NikkeCardSortFilterActions>();
    private readonly InputAction m_UI_NikkeCardSortFilter_Close;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI_NikkeCardSortFilter".
    /// </summary>
    public struct UI_NikkeCardSortFilterActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UI_NikkeCardSortFilterActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI_NikkeCardSortFilter/Close".
        /// </summary>
        public InputAction @Close => m_Wrapper.m_UI_NikkeCardSortFilter_Close;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI_NikkeCardSortFilter; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UI_NikkeCardSortFilterActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UI_NikkeCardSortFilterActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UI_NikkeCardSortFilterActions" />
        public void AddCallbacks(IUI_NikkeCardSortFilterActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_NikkeCardSortFilterActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_NikkeCardSortFilterActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UI_NikkeCardSortFilterActions" />
        private void UnregisterCallbacks(IUI_NikkeCardSortFilterActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UI_NikkeCardSortFilterActions.UnregisterCallbacks(IUI_NikkeCardSortFilterActions)" />.
        /// </summary>
        /// <seealso cref="UI_NikkeCardSortFilterActions.UnregisterCallbacks(IUI_NikkeCardSortFilterActions)" />
        public void RemoveCallbacks(IUI_NikkeCardSortFilterActions instance)
        {
            if (m_Wrapper.m_UI_NikkeCardSortFilterActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UI_NikkeCardSortFilterActions.AddCallbacks(IUI_NikkeCardSortFilterActions)" />
        /// <seealso cref="UI_NikkeCardSortFilterActions.RemoveCallbacks(IUI_NikkeCardSortFilterActions)" />
        /// <seealso cref="UI_NikkeCardSortFilterActions.UnregisterCallbacks(IUI_NikkeCardSortFilterActions)" />
        public void SetCallbacks(IUI_NikkeCardSortFilterActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_NikkeCardSortFilterActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_NikkeCardSortFilterActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UI_NikkeCardSortFilterActions" /> instance referencing this action map.
    /// </summary>
    public UI_NikkeCardSortFilterActions @UI_NikkeCardSortFilter => new UI_NikkeCardSortFilterActions(this);

    // UI_NikkeDetailPopup
    private readonly InputActionMap m_UI_NikkeDetailPopup;
    private List<IUI_NikkeDetailPopupActions> m_UI_NikkeDetailPopupActionsCallbackInterfaces = new List<IUI_NikkeDetailPopupActions>();
    private readonly InputAction m_UI_NikkeDetailPopup_Close;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI_NikkeDetailPopup".
    /// </summary>
    public struct UI_NikkeDetailPopupActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UI_NikkeDetailPopupActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI_NikkeDetailPopup/Close".
        /// </summary>
        public InputAction @Close => m_Wrapper.m_UI_NikkeDetailPopup_Close;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI_NikkeDetailPopup; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UI_NikkeDetailPopupActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UI_NikkeDetailPopupActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UI_NikkeDetailPopupActions" />
        public void AddCallbacks(IUI_NikkeDetailPopupActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_NikkeDetailPopupActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_NikkeDetailPopupActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UI_NikkeDetailPopupActions" />
        private void UnregisterCallbacks(IUI_NikkeDetailPopupActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UI_NikkeDetailPopupActions.UnregisterCallbacks(IUI_NikkeDetailPopupActions)" />.
        /// </summary>
        /// <seealso cref="UI_NikkeDetailPopupActions.UnregisterCallbacks(IUI_NikkeDetailPopupActions)" />
        public void RemoveCallbacks(IUI_NikkeDetailPopupActions instance)
        {
            if (m_Wrapper.m_UI_NikkeDetailPopupActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UI_NikkeDetailPopupActions.AddCallbacks(IUI_NikkeDetailPopupActions)" />
        /// <seealso cref="UI_NikkeDetailPopupActions.RemoveCallbacks(IUI_NikkeDetailPopupActions)" />
        /// <seealso cref="UI_NikkeDetailPopupActions.UnregisterCallbacks(IUI_NikkeDetailPopupActions)" />
        public void SetCallbacks(IUI_NikkeDetailPopupActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_NikkeDetailPopupActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_NikkeDetailPopupActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UI_NikkeDetailPopupActions" /> instance referencing this action map.
    /// </summary>
    public UI_NikkeDetailPopupActions @UI_NikkeDetailPopup => new UI_NikkeDetailPopupActions(this);

    // UI_NikkeLevelUpPopup
    private readonly InputActionMap m_UI_NikkeLevelUpPopup;
    private List<IUI_NikkeLevelUpPopupActions> m_UI_NikkeLevelUpPopupActionsCallbackInterfaces = new List<IUI_NikkeLevelUpPopupActions>();
    private readonly InputAction m_UI_NikkeLevelUpPopup_Close;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI_NikkeLevelUpPopup".
    /// </summary>
    public struct UI_NikkeLevelUpPopupActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UI_NikkeLevelUpPopupActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI_NikkeLevelUpPopup/Close".
        /// </summary>
        public InputAction @Close => m_Wrapper.m_UI_NikkeLevelUpPopup_Close;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI_NikkeLevelUpPopup; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UI_NikkeLevelUpPopupActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UI_NikkeLevelUpPopupActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UI_NikkeLevelUpPopupActions" />
        public void AddCallbacks(IUI_NikkeLevelUpPopupActions instance)
        {
            if (instance == null || m_Wrapper.m_UI_NikkeLevelUpPopupActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UI_NikkeLevelUpPopupActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UI_NikkeLevelUpPopupActions" />
        private void UnregisterCallbacks(IUI_NikkeLevelUpPopupActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UI_NikkeLevelUpPopupActions.UnregisterCallbacks(IUI_NikkeLevelUpPopupActions)" />.
        /// </summary>
        /// <seealso cref="UI_NikkeLevelUpPopupActions.UnregisterCallbacks(IUI_NikkeLevelUpPopupActions)" />
        public void RemoveCallbacks(IUI_NikkeLevelUpPopupActions instance)
        {
            if (m_Wrapper.m_UI_NikkeLevelUpPopupActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UI_NikkeLevelUpPopupActions.AddCallbacks(IUI_NikkeLevelUpPopupActions)" />
        /// <seealso cref="UI_NikkeLevelUpPopupActions.RemoveCallbacks(IUI_NikkeLevelUpPopupActions)" />
        /// <seealso cref="UI_NikkeLevelUpPopupActions.UnregisterCallbacks(IUI_NikkeLevelUpPopupActions)" />
        public void SetCallbacks(IUI_NikkeLevelUpPopupActions instance)
        {
            foreach (var item in m_Wrapper.m_UI_NikkeLevelUpPopupActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UI_NikkeLevelUpPopupActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UI_NikkeLevelUpPopupActions" /> instance referencing this action map.
    /// </summary>
    public UI_NikkeLevelUpPopupActions @UI_NikkeLevelUpPopup => new UI_NikkeLevelUpPopupActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "None" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="NoneActions.AddCallbacks(INoneActions)" />
    /// <seealso cref="NoneActions.RemoveCallbacks(INoneActions)" />
    public interface INoneActions
    {
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI_PopupTest" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UI_PopupTestActions.AddCallbacks(IUI_PopupTestActions)" />
    /// <seealso cref="UI_PopupTestActions.RemoveCallbacks(IUI_PopupTestActions)" />
    public interface IUI_PopupTestActions
    {
        /// <summary>
        /// Method invoked when associated input action "Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClose(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI_ItemDetailPopup" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UI_ItemDetailPopupActions.AddCallbacks(IUI_ItemDetailPopupActions)" />
    /// <seealso cref="UI_ItemDetailPopupActions.RemoveCallbacks(IUI_ItemDetailPopupActions)" />
    public interface IUI_ItemDetailPopupActions
    {
        /// <summary>
        /// Method invoked when associated input action "Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClose(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI_TabGroupPopup" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UI_TabGroupPopupActions.AddCallbacks(IUI_TabGroupPopupActions)" />
    /// <seealso cref="UI_TabGroupPopupActions.RemoveCallbacks(IUI_TabGroupPopupActions)" />
    public interface IUI_TabGroupPopupActions
    {
        /// <summary>
        /// Method invoked when associated input action "Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClose(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI_MissionPopup" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UI_MissionPopupActions.AddCallbacks(IUI_MissionPopupActions)" />
    /// <seealso cref="UI_MissionPopupActions.RemoveCallbacks(IUI_MissionPopupActions)" />
    public interface IUI_MissionPopupActions
    {
        /// <summary>
        /// Method invoked when associated input action "Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClose(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI_NikkeCardSortFilter" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UI_NikkeCardSortFilterActions.AddCallbacks(IUI_NikkeCardSortFilterActions)" />
    /// <seealso cref="UI_NikkeCardSortFilterActions.RemoveCallbacks(IUI_NikkeCardSortFilterActions)" />
    public interface IUI_NikkeCardSortFilterActions
    {
        /// <summary>
        /// Method invoked when associated input action "Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClose(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI_NikkeDetailPopup" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UI_NikkeDetailPopupActions.AddCallbacks(IUI_NikkeDetailPopupActions)" />
    /// <seealso cref="UI_NikkeDetailPopupActions.RemoveCallbacks(IUI_NikkeDetailPopupActions)" />
    public interface IUI_NikkeDetailPopupActions
    {
        /// <summary>
        /// Method invoked when associated input action "Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClose(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI_NikkeLevelUpPopup" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UI_NikkeLevelUpPopupActions.AddCallbacks(IUI_NikkeLevelUpPopupActions)" />
    /// <seealso cref="UI_NikkeLevelUpPopupActions.RemoveCallbacks(IUI_NikkeLevelUpPopupActions)" />
    public interface IUI_NikkeLevelUpPopupActions
    {
        /// <summary>
        /// Method invoked when associated input action "Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClose(InputAction.CallbackContext context);
    }
}
